src/objects/Cart__c.object
<CustomObject>
    <fields>
        <fullName>UserId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Carts2</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Cart</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Cart Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Carts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CartItem.object
<CustomObject>
    <fields>
        <fullName>StartDate__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/CartItem__c.object
<CustomObject>
    <fields>
        <fullName>CartId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cart</label>
        <referenceTo>Cart__c</referenceTo>
        <relationshipLabel>Cart Items</relationshipLabel>
        <relationshipName>Cart_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EndDate__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ProductId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipName>Carts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Totalprice__c</fullName>
        <label>Total price</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Cart Item</label>
    <nameField>
        <displayFormat>CN-{0000}</displayFormat>
        <label>Cart Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cart Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CartController.cls
public with sharing class CartController {
    @AuraEnabled
    public static String addToCart(Date startDate, Date endDate, String userId, 
                                    Integer totalPrice, String productId) {
        try {
            List<Cart__c> userCart = [SELECT 
                                        Id 
                                        FROM Cart__c 
                                        WHERE UserId__c = :userId LIMIT 1];
            if(userCart.isEmpty()) {
                Cart__c newCart = new Cart__c();
                newCart.UserId__c = userId;
                insert newCart;  
            }
            userCart = [SELECT 
                                        Id 
                                        FROM Cart__c 
                                        WHERE UserId__c = :userId LIMIT 1];
            CartItem__c cartItem = new CartItem__c();
            cartItem.CartId__c = userCart[0].Id;
            cartItem.ProductId__c = productId;
            cartItem.StartDate__c = startDate;
            cartItem.EndDate__c = endDate;
            cartItem.Totalprice__c = totalPrice;
            insert cartItem;
            return 'SUCCESS';
        } catch (Exception e) {
            return 'FAILURE';
        }
    }

    @AuraEnabled
    public static List<CartItem__c> getUserCart(String userId) {
        List<CartItem__c> cartItems = new List<CartItem__c>();
        try {
            cartItems = [SELECT Id, StartDate__c, EndDate__c, Totalprice__c, ProductId__c, CartId__c FROM CartItem__c WHERE CartId__r.UserId__c = :userId];
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
        return cartItems;
    }

    @AuraEnabled
    public static void deleteFromCart(String cartItemId) {
        try {
            Database.delete(cartItemId);
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled
    public static void editCartItem(String cartItemId, Date startDate, Date endDate, Double totalPrice) {
        try {
            CartItem__c cartItem = [SELECT Id, StartDate__c, EndDate__c, Totalprice__c FROM CartItem__c WHERE Id = :cartItemId LIMIT 1];
            cartItem.StartDate__c = startDate;
            cartItem.EndDate__c = endDate;
            cartItem.Totalprice__c = totalPrice;
            update cartItem;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}