src/objects/Cart__c.object
<CustomObject>
    <fields>
        <fullName>UserId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Carts2</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Cart</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Cart Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Carts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CartItem__c.object
<CustomObject>
    <fields>
        <fullName>CartId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cart</label>
        <referenceTo>Cart__c</referenceTo>
        <relationshipLabel>Cart Items</relationshipLabel>
        <relationshipName>Cart_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProductId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipName>Carts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Totalprice__c</fullName>
        <label>Total price</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Cart Item</label>
    <nameField>
        <displayFormat>CN-{0000}</displayFormat>
        <label>Cart Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cart Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Order.object
<CustomObject>
    <fields>
        <fullName>TotalPrice__c</fullName>
        <label>Total Price</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/OrderControllerTest.cls
@IsTest
public with sharing class OrderControllerTest {
    @IsTest
    static void testFailMakeNewOrder() {
        List<CartItem__c> cartItems = [SELECT Id FROM CartItem__c LIMIT 3];

        String response = OrdersController.makeNewOrder(cartItems, 1000);

        System.assert(true, response != 'SUCCESS');
    }

    @IsTest
    static void testSuccessMakeNewOrder() {
        Account acc = new Account();
        acc.Name = 'Customers';
        insert acc;
        Product2 prod = new Product2();
        prod.Name = 'SubUWU';
        insert prod;
        Cart__c newCart = new Cart__c();
        newCart.UserId__c = UserInfo.getUserId();
        CartItem__c cartIt = new CartItem__c();
        cartIt.CartId__c = newCart.Id;
        cartIt.ProductId__c = prod.Id;
        insert cartIt;
        List<CartItem__c> cartItems = new List<CartItem__c>();
        cartItems.add(cartIt);

        String response = OrdersController.makeNewOrder(cartItems, 1000);

        System.assertEquals('SUCCESS', response);
    }

    @IsTest
    static void testGetUserOrders() {
        Account acc = new Account();
        acc.Name = 'Customers';
        insert acc;
        Pricebook2 pricebook = new Pricebook2();
        pricebook.Name = 'Christmas Discount';
        insert pricebook;
        Order ord = new Order();
        ord.TotalPrice__c = 1499;
        ord.EffectiveDate = System.today();
        ord.Status = 'Draft';
        ord.OwnerId = UserInfo.getUserId();
        ord.AccountId = acc.Id;
        ord.Pricebook2Id = pricebook.Id;
        insert ord;

        Test.startTest();
        List<Order> userOrders = OrdersController.getUserOrders(UserInfo.getUserId());
        Test.stopTest();

        System.assert(true, userOrders != null);
    }

    @IsTest
    static void testGetOrderItems() {
        Account acc = new Account();
        acc.Name = 'Customers';
        insert acc;
        Pricebook2 pricebook = new Pricebook2();
        pricebook.Name = 'Christmas Discount';
        insert pricebook;
        Order ord = new Order();
        ord.TotalPrice__c = 1499;
        ord.EffectiveDate = System.today();
        ord.Status = 'Draft';
        ord.OwnerId = UserInfo.getUserId();
        ord.AccountId = acc.Id;
        ord.Pricebook2Id = pricebook.Id;
        insert ord;

        List<OrderItem> orderItems = OrdersController.getOrderItems(ord.Id);

        System.assert(true, orderItems != null);
    }
}