src/objects/Cart__c.object
<CustomObject>
    <fields>
        <fullName>UserId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Carts2</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Cart</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Cart Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Carts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CartItem__c.object
<CustomObject>
    <label>Cart Item</label>
    <nameField>
        <displayFormat>CN-{0000}</displayFormat>
        <label>Cart Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cart Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CartControllerTest.cls
@IsTest
public with sharing class CartControllerTest {

    @IsTest
    static void testSuccessAddToCart() {
        Date date1 = Date.newInstance(2023, 01, 30);
        Date date2 = Date.newInstance(2023, 01, 31);
        Product2 prod = new Product2();
        prod.Name = 'SubUWU';
        insert prod;

        Test.startTest();
        String response = CartController.addToCart(date1, date2, UserInfo.getUserId(), 900, prod.Id);
        Test.stopTest();

        System.assertEquals('SUCCESS', response);
    }

    @IsTest
    static void testSuccessGetUserCart() {
        Cart__c newCart = new Cart__c();
        newCart.UserId__c = UserInfo.getUserId();
        insert newCart;

        List<CartItem__c> cartItems = CartController.getUserCart(UserInfo.getUserId());

        System.assert(true, cartItems.isEmpty());
    }

    @IsTest
    static void testFailGetUserCart() {
        try {
            List<CartItem__c> cartItems = CartController.getUserCart('');
        } catch(Exception e) {
            System.assert(true, e.getMessage() != null);
        }
    }

    @IsTest
    static void testFailDeleteFromCart() {
        try {
            CartController.deleteFromCart('');
        } catch(Exception e) {
            System.assert(true, e.getMessage() != null);
        }
    }
}