src/objects/Cart__c.object
<CustomObject>
    <fields>
        <fullName>UserId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Carts2</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Cart</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Cart Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Carts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CartItem.object
<CustomObject>
    <fields>
        <fullName>StartDate__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/CartItem__c.object
<CustomObject>
    <fields>
        <fullName>CartId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cart</label>
        <referenceTo>Cart__c</referenceTo>
        <relationshipLabel>Cart Items</relationshipLabel>
        <relationshipName>Cart_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EndDate__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ProductId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipName>Carts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Totalprice__c</fullName>
        <label>Total price</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Cart Item</label>
    <nameField>
        <displayFormat>CN-{0000}</displayFormat>
        <label>Cart Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cart Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Order.object
<CustomObject>
    <fields>
        <fullName>TotalPrice__c</fullName>
        <label>Total Price</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/OrderItem.object
<CustomObject>
    <fields>
        <fullName>EndDate__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
</CustomObject>

src/classes/OrdersController.cls
public with sharing class OrdersController {
    @AuraEnabled
    public static String makeNewOrder(List<CartItem__c> cartItems, Integer fullPrice) {
        try {
            Cart__c cart = [SELECT Id, UserId__c FROM Cart__c WHERE Id = :cartItems[0].CartId__c LIMIT 1];
            Account acc = [SELECT Id FROM Account WHERE Name = 'Customers' LIMIT 1];
            Pricebook2 pricebook = [SELECT Id FROM Pricebook2 WHERE IsStandard = true LIMIT 1];
            Order newOrder = new Order();
            newOrder.AccountId = acc.Id;
            newOrder.OwnerId = cart.UserId__c;
            newOrder.EffectiveDate = System.today();
            newOrder.TotalPrice__c = fullPrice;
            newOrder.Status = 'Draft';
            newOrder.Pricebook2Id = pricebook.Id;
            insert newOrder;
            List<OrderItem> orderItems = new List<OrderItem>();
            for(CartItem__c cartItem : cartItems) {
                PricebookEntry pbe = [SELECT Id FROM PricebookEntry WHERE Product2Id = :cartItem.ProductId__c AND Pricebook2Id = :pricebook.Id];
                OrderItem orderItem = new OrderItem();
                orderItem.Product2Id = cartItem.ProductId__c;
                orderItem.StartDate__c = cartItem.StartDate__c;
                orderItem.EndDate__c = cartItem.EndDate__c;
                orderItem.OrderId = newOrder.Id;
                orderItem.UnitPrice = cartItem.Totalprice__c;
                orderItem.PricebookEntryId = pbe.Id;
                orderItem.Quantity = 1;
                orderItems.add(orderItem);
            }
            insert orderItems;
            newOrder.Status = 'Activated';
            update newOrder;
            delete cart;
            delete cartItems;
            return 'SUCCESS';
        } catch (Exception e) {
            return e.getMessage();
        }
    }

    @AuraEnabled
    public static List<Order> getUserOrders(String userId) {
        List<Order> userOrders = new List<Order>();
        try {
            userOrders = [SELECT Id, OrderNumber, TotalPrice__c, EffectiveDate FROM Order WHERE OwnerId = :userId];
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
        return userOrders;
    }

    @AuraEnabled
    public static List<OrderItem> getOrderItems(String orderId) {
        List<OrderItem> orderItems = new List<OrderItem>();
        try {
            orderItems = [SELECT Id, Product2.Name, Product2Id, StartDate__c, EndDate__c, UnitPrice FROM OrderItem WHERE OrderId = :orderId];
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
        return orderItems;
    }
}