src/objects/Credentials__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Password__c</fullName>
        <label>Password</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Username__c</fullName>
        <label>Username</label>
        <type>Email</type>
    </fields>
    <label>Credentials</label>
</CustomObject>

src/classes/HA_LoginSoap.cls
/**
 * Created by bartosz.rozpara on 25.10.2022.
 */

public with sharing class HA_LoginSoap {
    public static soapSforceComSchemasClassSoapwebser.SoapWebService soapWebService { get; set; }

    public static soapSforceComSchemasClassSoapwebser.SoapWebService login(String username) {
        partnerSoapSforceCom.Soap partnerSoap = new partnerSoapSforceCom.Soap();

        Credentials__c credential = [SELECT Username__c, Password__c FROM Credentials__c WHERE Username__c = :username];
        partnerSoapSforceCom.LoginResult loginResult = partnerSoap.login(credential.Username__c, credential.Password__c);
        soapSforceComSchemasClassSoapwebser.SessionHeader_element sessionHeaderElement = new soapSforceComSchemasClassSoapwebser.SessionHeader_element();
        sessionHeaderElement.sessionId = loginResult.sessionId;

        soapWebService = new soapSforceComSchemasClassSoapwebser.SoapWebService();
        soapWebService.SessionHeader = sessionHeaderElement;
        return soapWebService;
    }
}