src/objects/Doctor__c.object
<CustomObject>
    <fields>
        <fullName>FirstName__c</fullName>
        <label>FirstName</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LastName__c</fullName>
        <label>LastName</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Doctor</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Doctors</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/HA_DoctorTriggerController.cls
/**
 * Created by bartosz.rozpara on 01.11.2022.
 */

public with sharing class HA_DoctorTriggerController extends HA_TriggerHandler {
    public List<Doctor__c> newContracts;
    public List<Doctor__c> oldContracts;

    public HA_DoctorTriggerController() {
        this.newContracts = (List<Doctor__c>) Trigger.New;
        this.oldContracts = (List<Doctor__c>) Trigger.Old;
    }

    public override void beforeInsert() {
        for(Doctor__c doctor : newContracts) {
            doctor.Name = doctor.FirstName__c + ' ' + doctor.LastName__c;
        }
    }

    public override void beforeUpdate() {
        for(Doctor__c doctor : newContracts) {
            doctor.Name = doctor.FirstName__c + ' ' + doctor.LastName__c;
        }
    }
}