src/objects/Doctor__c.object
<CustomObject>
    <fields>
        <fullName>Birth_Date__c</fullName>
        <inlineHelpText>Date of birth of the doctor</inlineHelpText>
        <label>Birth Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Country</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <caseSensitive>true</caseSensitive>
        <label>Email</label>
        <required>true</required>
        <type>Email</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>FullName__c</fullName>
        <formula>FirstName__c  &amp; &quot; &quot; &amp; LastName__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>FullName</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PhoneNumber__c</fullName>
        <label>PhoneNumber</label>
        <type>Phone</type>
    </fields>
    <label>Doctor</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Doctors</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/HA_RandomDoctors.cls
/**
 * Created by bartosz.rozpara on 14.10.2022.
 */

public with sharing class HA_RandomDoctors {
    public List<Doctor__c> doctors { get; set; }
    public List<Doctor__c> randomDoctors { get; set; }
    public List<Integer> randomList { get; set; }
    public Integer listSize { get; set; }
    private Integer itemCounter { get; set; }

    public HA_RandomDoctors() {
        searchRandomDoctors();
    }

    public void searchRandomDoctors() {
        itemCounter = 5;
        Integer randomRecordNumber;
        randomList = new List<Integer>();
        randomDoctors = new List<Doctor__c>();

        doctors = [SELECT FullName__c, Country__c, Email__c, PhoneNumber__c, Birth_Date__c FROM Doctor__c];
        listSize = doctors.size() - 2;
        randomList.add(Math.round(Math.random() * listSize));
        do{
            randomRecordNumber = Math.round(Math.random() * listSize);
            if(!randomList.contains(randomRecordNumber)){
                randomList.add(randomRecordNumber);
            }

        }while(randomList.size() < 5 );

        for(Integer item : randomList) {
            randomDoctors.add(doctors[item]);
        }
    }
}